server.port=8443

jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/student_mis?useUnicode=true&characterEncoding=utf8&useSSL=false
jdbc.username=${DB_USERNAME:root}
jdbc.password=${DB_PASSWORD:root}

#mybatis
mybatis_config_file=mybatis-config.xml
mapper_path=/mapper/*/**.xml
entity_package=com.szh.sms.dto

# Logging
logging.level.com.szh.sms.service.MailService=DEBUG

# Mail
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=1347430848@qq.com
spring.mail.password=ywuoqzkzzzoohagi
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.qq.com
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
